####################################################
# +----------------------------------------------+ #
# |                DistantScythes                | #
# +----------------------------------------------+ #
####################################################

# This section lists all valid scythe IDs.

scythes:
  - "wooden_scythe"
  - "iron_scythe"


